cf_instance: 'rcs'
cf_prefix: '/srv'
cf_app_name: "{{ cf_instance }}-cf-app"
cf_workers_name: "{{ cf_instance }}-cf-workers"
cf_dir: "{{ cf_prefix }}/{{ cf_app_name }}"
cf_image: 'docker.io/ubccr/coldfront:latest'
cf_bind_host: '0.0.0.0'
cf_bind_port: '8000'
cf_timezone: local
cf_network: "{{ cf_instance }}-cf-net"

# web server
cf_web_name: "{{ cf_instance }}-cf-web"
cf_web_image: docker.io/library/nginx:1.27-alpine
cf_web_dir: "{{ cf_prefix }}/{{ cf_web_name }}"
cf_web_bind_host: "{{ cf_bind_host }}"
cf_web_bind_port: '80'

# database
cf_db_managed: true
cf_db_image: docker.io.library/postgres:16
cf_db_name: "{{ cf_instance }}-cf-pgsql"
cf_db_dir: "{{ cf_prefix }}/{{ cf_db_name }}"
cf_db_host: "{{ cf_db_name }}"
cf_db_dbname: "coldfront"
cf_db_user: "{{ cf_instnace }}"
cf_db_password: ""

# redis
cf_redis_managed: true
cf_redis_name: "{{ cf_instance }}-cf-redis"
cf_redis_image: docker.io/library/redis:7
cf_redis_host: "{{ cf_redis_name }}
