---
- name: Create Coldfront top level directories
  ansible.builtin.file:
    path: "{{ cf_dir }}/{{ item.dir }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  loop:
    - { dir: "" }
    - { dir: "static" }

- name: Create Coldfront webserver top level directories
  ansible.builtin.file:
    path: "{{ cf_web_dir }}/{{ item.dir }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  loop:
    - { dir: "" }

- name: Create Coldfront instance network
  containers.podman.podman_network:
    name: "{{ cf_network }}"
    state: present

- name: Handle Coldfront Postgres password
  ansible.builtin.include_tasks: secret.yml
  vars:
    cf_secret_var: cf_db_password

- name: Create Postgres database for Coldfront
  ansible.builtin.import_tasks: deploy_postgres.yml
  when: cf_db_managed is true

- name: Create Redis server for Coldfront
  ansible.builtin.import_tasks: deploy_redis.yml
  when: cf_redis_managed is true

- name: Create Coldfront webserver container
  containers.podman.podman_container:
    name: "{{ cf_web_name }}"
    image: "{{ cf_web_image }}"
    network: "{{ cf_network }}"
    publish: "{{ cf_web_bind_host }}:{{ cf_web_bind_port }}:80"
    timezone: "{{ cf_timezone }}"
    volumes:
      - "{{ cf_dir }}/static:/usr/share/nginx/html:ro,z"
    state: quadlet
    quadlet_filename: "{{ cf_web_name }}"
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target
  notify: Restart Coldfront webserver

- name: Install Coldfront config files
  ansible.builtin.template:
    src: "{{ item.file }}.j2"
    dest: "{{ cf_dir }}/{{ item.file }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0640') }}"
  loop:
    - { file: "coldfront_settings.py" }
    - { file: "coldfront.env" }
  notify: Restart Coldfront server

- name: Create Coldfront app container
  containers.podman.podman_container:
    name: "{{ cf_app_name }}"
    image: "{{ cf_image }}"
    network: "{{ cf_network }}"
    publish: "{{ cf_bind_host }}:{{ cf_bind_port }}:8000"
    timezone: "{{ cf_timezone }}"
    env_file: "{{ cf_dir }}/coldfront.env"
    secrets:
      - "{{ cf_instance }}_cf_db_password,type=mount,target=/run/secrets/cf_db_password"
    volumes:
      - "{{ cf_dir }}/coldfront_settings.py:/etc/coldfront_settings.py:ro,Z"
      - "{{ cf_dir }}/static:/static:rw,z"
    state: quadlet
    quadlet_filename: "{{ cf_app_name }}"
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target
  notify: Restart Coldfront server

- name: Enable Coldfront systemd services
  ansible.builtin.systemd:
    name: "{{ item }}"
    daemon_reload: true
    enabled: true
  when: not ansible_check_mode
  loop:
    - "{{ cf_web_name }}"
    - "{{ cf_app_name }}"
